### ISSUE TITLE
Cannot use templates from catalog 

### ISSUE THREAD

**Issue by fruboes** [kubevirt-ui/kubevirt-plugin#1159]
I'm using OKD 1.12 and kubevirt plugin pulled by kubevirt-hyperconverged 1.8.1 (quay.io/kubevirt-ui/kubevirt-plugin@sha256:253cb213f052faec5b41e56860133ebb7508715f6abe691b2609c9e36dec62ab
)

With that I'm not able to use  templates from Virtualization/Catalog. I get "Error Loading Template: the server could not find the requested resource Please try again" message after clicking "Customize virtualmachine" for selected template. 

This happens unless I select "All projects" from the project selection dropdown at top. This way it works, but leads to vm created in default namespace (and works only for "administrator" perspective - for developer I always get the mentioned error.

**Comment by tiraboschi** [comment]
@upalatucci can you please take a look?

**Comment by tiraboschi** [comment]
On the HCO side we are only consuming tagged versions for OKD Virtualization releases.
Here the latest tag on 4.12 branch is from Nov 16 ( https://github.com/kubevirt-ui/kubevirt-plugin/releases/tag/v4.12.0 ).
And so the correspondent image under https://quay.io/repository/kubevirt-ui/kubevirt-plugin?tab=tags&tag=v4.12.0

All the fixes under https://github.com/kubevirt-ui/kubevirt-plugin/commits/release-4.12 after Nov 16 are simply waiting for the next v4.12.z tag (v4.12.1 in this case) in order to be really shipped.

**Comment by upalatucci** [comment]
Hi guys, we fixed our automation and now it's available a new tag on quay.io for 4.12 called `v4.12.3`.
